---
dist: bionic
language: ruby
cache: bundler

env:
  - LIBSSL_V=1.0
  - LIBSSL_V=

rvm:
  - ruby-head
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9

gemfile:
  - gemfiles/openssl_head.gemfile
  - gemfiles/openssl_2_1.gemfile
  - gemfiles/openssl_2_0.gemfile
  - gemfiles/openssl_default.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/openssl_head.gemfile

install:
  - sudo apt install libssl${LIBSSL_V}-dev
  - rvm reinstall $TRAVIS_RUBY_VERSION --autolibs=disable
  - gem install bundler -v "~> 2.0"
  - rm Gemfile.lock
  - bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
