---
dist: bionic
language: ruby
cache: bundler

env:
  - RB=2.7.1 LIBSSL=1.0
  - RB=2.7.1 LIBSSL=1.1
  - RB=2.6.6 LIBSSL=1.0
  - RB=2.6.6 LIBSSL=1.1
  - RB=2.5.8 LIBSSL=1.0
  - RB=2.5.8 LIBSSL=1.1
  - RB=2.4.10 LIBSSL=1.0
  - RB=2.4.10 LIBSSL=1.1
  - RB=ruby-head LIBSSL=1.0
  - RB=ruby-head LIBSSL=1.1

gemfile:
  - gemfiles/openssl_head.gemfile
  - gemfiles/openssl_2_1.gemfile
  - gemfiles/openssl_2_0.gemfile
  - gemfiles/openssl_default.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - env: RB=ruby-head LIBSSL=1.0
    - env: RB=ruby-head LIBSSL=1.1
    - gemfile: gemfiles/openssl_head.gemfile

before_install:
  - ./install-openssl.sh
  - ./install-ruby.sh
  - gem install bundler -v "~> 2.0"
  - rm Gemfile.lock
